packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/react": ^19.0.2
  "@types/react-dom": ^19.0.2
  "@types/node": ^22.10.2
  next: 15.1.3
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.7.2
  lucide-react: ^0.469.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7


