packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@types/node": ^20.14.14
  next: 15.0.0-canary.157
  react: next
  react-dom: next
  typescript: ^5.6.1
  lucide-react: ^0.441.0
  tailwindcss: ^3.4.11
  tailwindcss-animate: ^1.0.7


