packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "@types/node": ^20
  next: 15.0.0-canary.86
  react: next
  react-dom: next
  typescript: ^5.5.4
  lucide-react: ^0.400.0
  tailwindcss: ^3
  tailwindcss-animate: ^1


