packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@types/node": ^22.9.3
  next: 15.0.3
  react: next
  react-dom: next
  typescript: ^5.7.2
  lucide-react: ^0.460.0
  tailwindcss: ^3.4.15
  tailwindcss-animate: ^1.0.7


