packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  '@types/node': ^22.13.8
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.8.2
  lucide-react: ^0.469.0
  tailwindcss: ^4.0.9
  tailwindcss-animate: ^1.0.7
  zod: ^3.24.2
onlyBuiltDependencies:
  - esbuild
